server:
  port:
    8080
  servlet:
    context-path: /
  application:
    name: authx

spring:
  jpa:
    open-in-view: false # 显式禁用
  #jpa:
  #  database-platform: org.hibernate.dialect.MySQLDialect
  #  show-sql: true
  #  properties:
  #    hibernate.physical_naming_strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
  #    hibernate:
  #      format_sql: true
  jackson:
    default-property-inclusion: non_null
  datasource:
    url: jdbc:mysql://localhost:3306/authenticate?characterEncoding=UTF-8&useSSL=false
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      minimum-idle: 5
      maximum-pool-size: 20
      idle-timeout: 30000
      pool-name: HikariPool
      max-lifetime: 1800000
      connection-timeout: 30000
  #h2:
  #  console:
  #    enabled: true

authX:
  enable-global-exception-handler: true
  generate-username:
    algorithm: MD5
    hash-length: 5
    counter-length: 3

token:
  signing:
    key: 413F4428472B4B6250655368566D5970337336763979244226452948404D6351

springdoc:
  api-docs:
    enabled: true
    path: /v3/api-docs
  swagger-ui:
    enabled: true
    path: /swagger-ui.html

logging:
  console:
    enabled: false  # 禁用控制台输出
  file:
    name: logs/application.log  # 设置日志文件路径和名称
    max-size: 10MB  # 日志文件最大大小
    max-history: 30  # 保留的日志文件历史数目
  pattern:
    file: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"  # 设置文件日志输出格式
  level:
    org.springframework: INFO  # 设置 Spring Framework 的日志级别
    org.gzdieheart.authx: DEBUG  # 设置自定义包 com.example 的日志级别

